### ISSUE TITLE
Bring configs uptodate with OAPIF Part 2 (CRS support)

### ISSUE THREAD

**Issue by justb4** [geopython/demo.pygeoapi.io#42]
Now that pygeoapi supports Part 2, it makes sense to upgrade various configs on the demo server to showcase. Although defaults (WGS84 with lon,lat axis ordering) apply, it would be good to show support and especially gear up for CITE tests.

Basically for each 'feature' provider the `crs` and `storageCRS` config params need to be added, for example:

```
        providers:
            - type: feature
              name: Elasticsearch
              data: http://elasticsearch_cite:9200/canada-hydat-daily-mean-02hc003
              id_field: IDENTIFIER
              time_field: DATE
# NEW
              crs:
                - http://www.opengis.net/def/crs/OGC/1.3/CRS84
                - http://www.opengis.net/def/crs/EPSG/0/4326
                - http://www.opengis.net/def/crs/EPSG/0/3348
              storage_crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
```

http://www.opengis.net/def/crs/OGC/1.3/CRS84 basically means WGS84 with lon,lat axis ordering, the default.

* `/cite` endpoint
* `/master` endpoint, also remove all `src_epsg` and `target_epsg` from OGR Providers. `src_epsg` should be replaced with corresponding `storage_crs`.
